### ISSUE TITLE
404: zipMoneyWidgetJs

### ISSUE THREAD

**Issue by brohiem** [zipMoney/magento2#58] opened 2019-07-29 17:20 UTC
Running Magento 2.2.4.

New to Magento.  Installed this module.  However on the checkout page we are getting a 404 when trying to load this script from the `http://local.mysite.com/static/version1564078640/frontend/MyVendor/mysite/en_US/zipMoneyWidgetJs.js`

I see in the requirejs-config.js file that its referencing the script in a secure remote location:
zipMoneyWidgetJs: 'https://static.zipmoney.com.au/lib/js/zm-widget-js/dist/zip-widget.min',

Would this problem be caused by the 'zipMoneyWidgetJs' file not being downloaded and put into the correct location because of permissions?

-----------------
requirejs-config.js
-----------------
...
require.config(config);
})();
(function() {
var config = {
    paths: {
        zipMoneyWidgetJs: 'https://static.zipmoney.com.au/lib/js/zm-widget-js/dist/zip-widget.min',
        zipMoneyCheckoutJs:'https://static.zipmoney.com.au/checkout/checkout-v1.min'
    }
};
...
----------------

![Screen Shot 2019-07-29 at 10 15 00 AM](https://user-images.githubusercontent.com/999907/62068170-55b68780-b1ea-11e9-9beb-369a525c906a.png)

**Comment by benzhangzip** [comment] 2019-10-11 01:54
Hi @brohiem 
Looks like the issue is because you want to merged our external JS into your theme JS, which will not work as this resource is hosted by us not included in your local file system.
Please do not try to merge our JS into yours

This JS is for display our logo and marketing related assets and need to load from our end, in case for any updates, like terms and condition or interest free period ect.
https://static.zipmoney.com.au/lib/js/zm-widget-js/dist/zip-widget.min.js

This JS is for checkout popup or redirect, and is required to loaded in checkout and not hosted by you site.
https://static.zipmoney.com.au/checkout/checkout-v1.min.js

If you are using third party JS merging into one big JS, then you might need to exclude this two JS thanks.

**Comment by benzhangzip** [comment] 2019-11-28 01:42
Closing this issue as it should be resolve in 1.0.10

**Closed by benzhangzip** 2019-11-28 01:42 UTC
