### ISSUE TITLE
After checkout, user sometimes redirected to cart page with error: Enter a valid payment method and try again

### ISSUE THREAD

**Issue by hieudmg** [zipMoney/magento2#67] opened 2019-12-05 10:14 UTC
After choosing zip payment and fill the required information, payment processed successfully. Sometimes user will be redirected to cart page unexpectedly with the error message below:

![error](https://user-images.githubusercontent.com/56947287/70225983-9f0f7880-1782-11ea-8516-9976a138bf47.png)

This is some lines from log:
```
[2019-12-05 05:02:06] zipMoneyLog.DEBUG: On Complete Controller [] []
[2019-12-05 05:02:06] zipMoneyLog.DEBUG: Result:- %s [] []
[2019-12-05 05:02:06] zipMoneyLog.DEBUG: Current Customer Id:- %s Quote Customer Id:- %s Quote checkout method:- %s [] []
[2019-12-05 05:02:06] zipMoneyLog.DEBUG: Quote Grand Total:- 2.1500 Quote Customer Id:- 14852 Checkout Method:- customer [] []
[2019-12-05 05:02:06] zipMoneyLog.DEBUG: Load customer from session. [] []
[2019-12-05 05:02:06] zipMoneyLog.DEBUG: Creating Order as Logged in Customer  [] []
[2019-12-05 05:02:06] zipMoneyLog.DEBUG: Enter a valid payment method and try again. [] []
```

**Comment by benzhangzip** [comment] 2019-12-16 22:53
Hi @hieudmg 

We are not able to reproduce this error, but from the error log messages, the user has customer account in Magento, and the error is coming from Quote validation Rule when try to create order, if  this issue happened for some user but not all of them then I think there might be issue on the multiple server setup for your project.

You might need to consider sticky session to make sure all AJAX request goes to the same server and if the place order redirect from zip side, landed in 2 or more requests to your backend servers then one server place the order successfully but another slow request also try to place order then it will failed. However the slow request return back last and redirect client to the error page instead of the successful page. This is just the theory, we need more logs from all servers to confirm that.

**Comment by benzhangzip** [comment] 2020-03-06 05:48
Hi @hieudmg ,

We have identify this error but it is not really related to the plugin, it is more related to the checkout theme or extensions that changing the behavior on the checkout page that looks like "onestepcheckout" like in Magento1

We reproduce the issue in some merchants, as they all using similar custom "onestepcheckout" theme that in the final place order click, they sometimes successfully call the "save payment method" some of them did not, if they don't save the selection of the payment method it will not be remember after you get redirect back from Zip website. So there is some conditional patches you could try:

`vendor/zipmoney/magento2/Model/Charge.php`

`In about line 560
   // HOTFIX
    $paymentMethod = $this->_quote->getPayment();
    if ($paymentMethod
      && $paymentMethod->getMethod() !== \ZipMoney\ZipMoneyPayment\Model\Ui\ConfigProvider::CODE) {
        $paymentMethod->setMethod(\ZipMoney\ZipMoneyPayment\Model\Ui\ConfigProvider::CODE);
        $paymentMethod->save();
    }
    // HOTFIX`

This hotfix code will help those merchants that do not want to help customer remember their payment selection

**Comment by benzhangzip** [comment] 2020-03-08 22:17
Closing this issue deal to the issue is causing by checkout payment method selecting either being reset on redirection or not saved Quote Payment in database that causing the issue, it is out of scope of single plugin could resolve, but solution provided, depends on developer to apply fix according to their customization.

**Closed by benzhangzip** 2020-03-08 22:17 UTC
