### ISSUE TITLE
Error while getting the redirect url

### ISSUE THREAD

**Issue by luan123z** [zipMoney/magento2#56] opened 2019-04-17 02:50 UTC
Hello.

I've installed the ZipMoney module and enabled it as sandbox mode.
However, I always get this error http://prntscr.com/nczl7a while trying to place an order.

**Comment by stephenbori** [comment] 2019-04-18 14:42
I am getting the exact same error - set to production mode as per Zip installation guides and module installed with composer. 

See log entry below:

Since activiating, we have only been able to process a single order (over a 12 day period) and had many failed attempts such as below within our logs

```
 [2019-04-18 10:38:29] zipMoneyLog.DEBUG: Errors:- 500 [] []
[2019-04-18 10:38:29] zipMoneyLog.DEBUG: Errors:- null [] []
[2019-04-18 10:38:29] zipMoneyLog.DEBUG: An error occurred while to requesting the redirect url. [] []
[2019-04-18 10:38:38] zipMoneyLog.INFO: Starting Checkout [] []
[2019-04-18 10:38:39] zipMoneyLog.DEBUG: Checkout Method:- guest [] []
[2019-04-18 10:38:39] zipMoneyLog.DEBUG: Is Allowed Guest Checkout :- 1 [] []
[2019-04-18 10:38:39] zipMoneyLog.DEBUG: Is Customer Logged In :-  [] []
[2019-04-18 10:38:39] zipMoneyLog.DEBUG: Product Id:- 176 Is Virtual:- No [] []
[2019-04-18 10:38:39] zipMoneyLog.DEBUG: Shipping Required:- Yes [] []
[2019-04-18 10:38:39] zipMoneyLog.DEBUG: Gift Card Amount:- 0 [] []
[2019-04-18 10:38:39] zipMoneyLog.DEBUG: Checkout Request:- {"type":"standard","shopper":{"first_name":"Stephen","last_name":"Hill","phone":7834758345345345,"email":"stephen@me.com","billing_address":{"line1":"test","city":"parramatta","state":"NSW","postal_code":"2150","country":"AU","first_name":"Stephen","last_name":"Hill"}},"order":{"reference":"2000006483","amount":2899.95,"currency":"AUD","shipping":{"pickup":false,"address":{"line1":"test","city":"parramatta","state":"NSW","postal_code":"2150","country":"AU","first_name":"Stephen","last_name":"Hill"}},"items":[{"name":"Ascende Maxi Bunk Bed","amount":2899.95,"reference":"14386","description":"<ul>\r\n<li>Made from solid European Beech<\/li>\r\n<li>Bed slats made from Australian Araucaria<\/li>\r\n<li>Available in Barley or Truffle and Barley<\/li>\r\n<li>Other sizes are available<\/li>\r\n<li>Mattress not included<\/li>\r\n<li>Requires assembly<\/li>\r\n<\/ul>\r\n<p><span>Bottom bunk requires mattress size 135 x 189cm<br \/><\/span>Top bunk requires mattress size 99 x 189cm<\/p>","quantity":1,"type":"sku","image_uri":"https:\/\/smhttp-ssl-77935.nexcesscdn.net\/au\/pub\/static\/version1555355490\/frontend\/Boori\/au\/en_AU\/Magento_Catalog\/images\/product\/placeholder\/.jpg","item_uri":"https:\/\/www.boori.com\/au\/ascende-maxi-bunk-bed-truffle-barley","product_code":"BK-ASMBB\/TB"}],"cart_reference":"33337"},"metadata":{},"config":{"redirect_uri":"https:\/\/www.boori.com\/au\/zipmoneypayment\/complete\/"}} [] []
```

**Comment by benzhangzip** [comment] 2019-04-23 02:08
![image](https://user-images.githubusercontent.com/42924127/56547172-ee23e700-65bf-11e9-8c27-63bbd52f075a.png)
Hi All this is very common issue we known, it is the payload phone number must be less than 16 characters, as if you know C# DotNet Core will try to parse this "number" like thing to number but lower than 16 overflow the integers and get fatal error on our API before reach our code, or validation, if you are entering pure number make sure it is shorter or convert it to string like "phone":"783475834534888", the double quote is important, and we could accept "+61 04000000000" and the actual limit is larger than 16, but when you submit us pure number then it must be smaller than integer limit.

**Comment by benzhangzip** [comment] 2019-04-23 02:12
We are planning to update all our plugins to resolve this issue, but in the mean time we do hope merchants could implement a validation on phone numbers thanks.

**Comment by stephenbori** [comment] 2019-04-23 10:57
@benzhangzip - Thanks for the heads up on above. This was actually a bad example on my part but good to know for future reference.  All other submissions by customers to date have had a phone number in AU format of fewer than 16 characters.

Trying on our staging site with real AU addresses (our head office etc) we still get the same generic checkout error and so based on this I am wondering if we are either passing other fields in the incorrect format or missing some data.

As we are using a 3rd party checkout (Amasty OneStepCheckout) it may not be passing the correct fields for the API as I presume it's configured only for the default magento/checkout module. 

Is it possible to send over a list of required API fields, validation etc so I can investigate further?

**Comment by benzhangzip** [comment] 2019-04-23 23:31
Hi @stephenbori 
You could always check on this page for API updates and specifications https://zip-online.api-docs.io/v1/api-specification/create-a-checkout it has all the required or not required fields specification, and it is also possible we could custom configure your account to skip checking any fields, but it is not recommended in terms of fraud detection. 
90% of the error is in the payload when try to create a checkout, balance for unit price and qty, shipping and grand total must be matched, discount and reward points or giftcard should be marked as negative items, you could check your payload log and you could use Postman to reproduce the issue easily if you already have your sandbox API key. Hope this helps

**Comment by stephenbori** [comment] 2019-05-08 07:49
@benzhangzip  - I have now resolved this issue by switching back to using magento's default checkout module and adding the following validation to the phone number under our magento_checkout within our design theme.

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="checkout.root">
            <arguments>
                <argument name="jsLayout" xsi:type="array">
                    <item name="components" xsi:type="array">
                        <item name="checkout" xsi:type="array">
                            <item name="children" xsi:type="array">
                                <item name="steps" xsi:type="array">
                                    <item name="children" xsi:type="array">
                                        <item name="shipping-step" xsi:type="array">
                                            <item name="children" xsi:type="array">
                                                <item name="shippingAddress" xsi:type="array">
                                                    <item name="children" xsi:type="array">
                                                        <item name="shipping-address-fieldset" xsi:type="array">                                                   
	                                                       <item name="children" xsi:type="array">
		                                                       <item name="telephone" xsi:type="array">
                                                                    <item name="config" xsi:type="array">
                                                                        <item name="tooltip" xsi:type="array">
                                                                           <item name="description" xsi:type="string" translate="true">We require your telephone number for delivery enquiries.</item>
                                                                        </item>
                                                                    </item>
                                                                      <item name="validation" xsi:type="array">
															        		<item name="max_text_length" xsi:type="number">13</item>
																		<item name="validate-number" xsi:type="number">0</item>
    																	</item>
                                                                </item>
	                                                        </item>
	                                                    </item>
                                                    </item>
                                                </item>
                                            </item>
                                        </item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>
    </body>
</page>

**Comment by benzhangzip** [comment] 2019-11-28 01:50
Close resolved issue

**Closed by benzhangzip** 2019-11-28 01:50 UTC

**Comment by vtransy** [comment] 2020-06-29 04:06
I get this error on Magento 2.2.4 event I enter correct AU phone No. Here is log

`[2020-06-29 04:04:07] zipMoneyLog.INFO: Starting Checkout [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Checkout Method:- guest [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Is Allowed Guest Checkout :- 1 [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Is Customer Logged In :-  [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Shipping Required:- Yes [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Gift Card Amount:- 0 [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: 133.1-0-0-133.1 [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Checkout Request:- {"type":"standard","shopper":{"first_name":"Max","last_name":"Me","phone":"0431632927","email":"testemail@gmail.com","billing_address":{"line1":"tetet","city":"tete","state":"VIC","postal_code":"4503","country":"AU","first_name":"Vong","last_name":"Tran"}},"order":{"reference":"000000848","amount":133.1,"currency":"AUD","shipping":{"pickup":false,"address":{"line1":"tetet","city":"tete","state":"VIC","postal_code":"4503","country":"AU","first_name":"my","last_name":"name"}},"items":[{"name":"Holden Colorado 7\/Isuzu MU-X 2013-on Formula Shock Absorber","amount":133.1,"reference":"11099","quantity":1,"type":"sku","image_uri":"https:\/\/imageapi.partsdb.com.au\/api\/Image?urlId=ShyE%2FqYHl4MjAqp7pe4Oe6DaGO4Uzh2mjp%2BRLScJfB4%3D","item_uri":"https:\/\/dev.mysite.com.au\/holden-colorado-7-isuzu-mu-x-2013-on-formula-shock-absorber-9972-50028-164013.html","product_code":"50028"}],"cart_reference":"33405"},"metadata":{},"config":{"redirect_uri":"https:\/\/dev.mysite.com.au\/zipmoneypayment\/complete\/"}} [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Errors:- {"error":{"code":"error_code"}} [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Errors:- 401 [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: Errors:- {} [] []
[2020-06-29 04:04:07] zipMoneyLog.DEBUG: An error occurred while to requesting the redirect url. [] []
`
What is the cause?

**Comment by benzhangzip** [comment] 2020-06-29 04:41
Hi @vtransy 
This is common error message for most of API users, when you get 401 error it is not related to incorrect payload but incorrect API keys, please double check your API key to make sure you are not using production key to sandbox environment, or using sandbox environment key to production.

**Comment by vtransy** [comment] 2020-06-29 04:49
Thank you @benzhangzip this is exactly my issue. I use live key for sandbox mode. I corrected it and now it's working.
