### ISSUE TITLE
Checkout Error with Configurable Product

### ISSUE THREAD

**Issue by KiuNguyen** [zipMoney/magento2#70] opened 2020-01-15 04:17 UTC
Hi, I got some issue with Zipmoney when I try to place an order with configurable product

Step:

- Create a configurable product (all child product has no weight)

![zipmoney1](https://user-images.githubusercontent.com/18417673/72404118-d9f3cb80-3786-11ea-8908-dbba24cfeb5c.png)

- Try to Place order with the product above 

![zipmoney2](https://user-images.githubusercontent.com/18417673/72404183-ff80d500-3786-11ea-9509-9593dd261ffe.png)

This is the log file zipMoneyPayment.log

`[2020-01-15 03:10:06] zipMoneyLog.INFO: Starting Checkout [] []
[2020-01-15 03:10:06] zipMoneyLog.DEBUG: Checkout Method:- guest [] []
[2020-01-15 03:10:06] zipMoneyLog.DEBUG: Is Allowed Guest Checkout :- 1 [] []
[2020-01-15 03:10:06] zipMoneyLog.DEBUG: Is Customer Logged In :-  [] []
[2020-01-15 03:10:06] zipMoneyLog.DEBUG: Shipping Required:- No [] []
[2020-01-15 03:10:06] zipMoneyLog.DEBUG: Gift Card Amount:- 0 [] []
[2020-01-15 03:10:06] zipMoneyLog.DEBUG: 150-0-0-150 [] []
[2020-01-15 03:10:06] zipMoneyLog.DEBUG: Checkout Request:- {"type":"standard","shopper":{"first_name":"kien","last_name":"nguyen","phone":"88888888","email":"kien.nguyen+88@balanceinternet.com.au","billing_address":{"line1":"121 Pockett Avenue","city":"Banks","state":"QLD","postal_code":"2906","country":"AU","first_name":"kien","last_name":"nguyen"}},"order":{"reference":"000000012","amount":150,"currency":"AUD","shipping":{"pickup":true},"items":[{"name":"config prod no weight","amount":150,"reference":"72","quantity":1,"type":"sku","image_uri":"https:\/\/pushys.local\/static\/frontend\/Magento\/luma\/en_AU\/Magento_Catalog\/images\/product\/placeholder\/.jpg","item_uri":"https:\/\/pushys.local\/config-prod-no-weight.html","product_code":"config prod no weight-1-2"}],"cart_reference":"33"},"metadata":{},"config":{"redirect_uri":"https:\/\/pushys.local\/zipmoneypayment\/complete\/"}} [] []
[2020-01-15 03:10:07] zipMoneyLog.DEBUG: Checkout Response:- {"id":"co_qKhdnzA0SwH8H1o6hzJJs1","uri":"https:\/\/my.sandbox.zipmoney.com.au\/?co=co_qKhdnzA0SwH8H1o6hzJJs1&m=20e7d8c2-1fb3-4941-9e57-1b0796344d37","type":"standard","shopper":{"first_name":"kien","last_name":"nguyen","phone":"88888888","email":"kien.nguyen+88@balanceinternet.com.au","birth_date":"0001-01-01T00:00:00+00:00","gender":"Other","statistics":{"sales_total_count":0,"sales_total_amount":0,"sales_avg_amount":0,"sales_max_amount":0,"refunds_total_amount":0,"previous_chargeback":false,"currency":"AUD"},"billing_address":{"line1":"121 Pockett Avenue","city":"Banks","state":"QLD","postal_code":"2906","country":"AU","first_name":"kien","last_name":"nguyen"}},"order":{"reference":"000000012","amount":150,"currency":"AUD","shipping":{"pickup":true},"items":[{"name":"config prod no weight","amount":150,"reference":"72","quantity":1,"type":"sku","image_uri":"https:\/\/pushys.local\/static\/frontend\/Magento\/luma\/en_AU\/Magento_Catalog\/images\/product\/placeholder\/.jpg","item_uri":"https:\/\/pushys.local\/config-prod-no-weight.html","product_code":"config prod no weight-1-2"}],"cart_reference":"33"},"config":{"redirect_uri":"https:\/\/pushys.local\/zipmoneypayment\/complete\/"},"created":"2020-01-15T03:10:07+00:00","state":"created","metadata":{}} [] []
[2020-01-15 03:10:07] zipMoneyLog.INFO: Successful to get redirect url [ https://my.sandbox.zipmoney.com.au/?co=co_qKhdnzA0SwH8H1o6hzJJs1&m=20e7d8c2-1fb3-4941-9e57-1b0796344d37 ]  [] []
[2020-01-15 03:11:02] zipMoneyLog.DEBUG: On Complete Controller [] []
[2020-01-15 03:11:02] zipMoneyLog.DEBUG: Result:- %s [] []
[2020-01-15 03:11:02] zipMoneyLog.DEBUG: Current Customer Id:- %s Quote Customer Id:- %s Quote checkout method:- %s [] []
[2020-01-15 03:11:03] zipMoneyLog.DEBUG: Quote Grand Total:- 150.0000 Quote Customer Id:-  Checkout Method:- guest [] []
[2020-01-15 03:11:06] zipMoneyLog.INFO: Successfull to place the order [] []
[2020-01-15 03:11:06] zipMoneyLog.DEBUG: Shipping Required:- Yes [] []
[2020-01-15 03:11:06] zipMoneyLog.DEBUG: Gift Card Amount:- 0 [] []
[2020-01-15 03:11:06] zipMoneyLog.DEBUG: 150-0-0-150 [] []
[2020-01-15 03:11:06] zipMoneyLog.DEBUG: Charge Payload:- {"authority":{"type":"checkout_id","value":"co_qKhdnzA0SwH8H1o6hzJJs1"},"amount":150,"currency":"AUD","capture":true,"order":{"reference":"000000012","shipping":{},"items":[{"name":"config prod no weight","amount":150,"reference":"17","quantity":1,"type":"sku","image_uri":"https:\/\/pushys.local\/static\/frontend\/Magento\/luma\/en_AU\/Magento_Catalog\/images\/product\/placeholder\/.jpg","item_uri":"https:\/\/pushys.local\/config-prod-no-weight.html","product_code":"config prod no weight-1-2"}]},"metadata":{}} [] []
[2020-01-15 03:11:07] zipMoneyLog.DEBUG: ApiError:- [400] Error connecting to the API (https://api.sandbox.zipmoney.com.au/merchant/v1/charges)-{"error":{"code":"request_invalid","message":"There are errors with the request, please see error items for more detail","details":[{"name":"Order.Shipping.Pickup","message":"Must have shipping address or allow pickup in store"}]}} [] []
[2020-01-15 03:11:07] zipMoneyLog.DEBUG: Cancelling the order [] []
[2020-01-15 03:11:07] zipMoneyLog.DEBUG: Could not process the payment [] []
[2020-01-15 03:11:08] zipMoneyLog.INFO: In errorAction [] []
[2020-01-15 03:11:08] zipMoneyLog.INFO: An error occurred. [] []
[2020-01-15 03:14:41] zipMoneyLog.INFO: Starting Checkout [] []
[2020-01-15 03:14:42] zipMoneyLog.DEBUG: Checkout Method:- guest [] []
[2020-01-15 03:14:42] zipMoneyLog.DEBUG: Is Allowed Guest Checkout :- 1 [] []
[2020-01-15 03:14:42] zipMoneyLog.DEBUG: Is Customer Logged In :-  [] []
[2020-01-15 03:14:42] zipMoneyLog.DEBUG: Shipping Required:- No [] []
[2020-01-15 03:14:42] zipMoneyLog.DEBUG: Gift Card Amount:- 0 [] []
[2020-01-15 03:14:42] zipMoneyLog.DEBUG: 150-0-0-150 [] []
[2020-01-15 03:14:42] zipMoneyLog.DEBUG: Checkout Request:- {"type":"standard","shopper":{"first_name":"kien","last_name":"nguyen","phone":"88888888","email":"kien.nguyen+88@balanceinternet.com.au","billing_address":{"line1":"121 Pockett Avenue","city":"Banks","state":"QLD","postal_code":"2906","country":"AU","first_name":"kien","last_name":"nguyen"}},"order":{"reference":"000000013","amount":150,"currency":"AUD","shipping":{"pickup":true},"items":[{"name":"config prod no weight","amount":150,"reference":"74","quantity":1,"type":"sku","image_uri":"https:\/\/pushys.local\/static\/frontend\/Magento\/luma\/en_AU\/Magento_Catalog\/images\/product\/placeholder\/.jpg","item_uri":"https:\/\/pushys.local\/config-prod-no-weight.html","product_code":"config prod no weight-1-2"}],"cart_reference":"34"},"metadata":{},"config":{"redirect_uri":"https:\/\/pushys.local\/zipmoneypayment\/complete\/"}} [] []
[2020-01-15 03:14:43] zipMoneyLog.DEBUG: Checkout Response:- {"id":"co_9od6Yvfkwas0BVZqwEPuD3","uri":"https:\/\/my.sandbox.zipmoney.com.au\/?co=co_9od6Yvfkwas0BVZqwEPuD3&m=20e7d8c2-1fb3-4941-9e57-1b0796344d37","type":"standard","shopper":{"first_name":"kien","last_name":"nguyen","phone":"88888888","email":"kien.nguyen+88@balanceinternet.com.au","birth_date":"0001-01-01T00:00:00+00:00","gender":"Other","statistics":{"sales_total_count":0,"sales_total_amount":0,"sales_avg_amount":0,"sales_max_amount":0,"refunds_total_amount":0,"previous_chargeback":false,"currency":"AUD"},"billing_address":{"line1":"121 Pockett Avenue","city":"Banks","state":"QLD","postal_code":"2906","country":"AU","first_name":"kien","last_name":"nguyen"}},"order":{"reference":"000000013","amount":150,"currency":"AUD","shipping":{"pickup":true},"items":[{"name":"config prod no weight","amount":150,"reference":"74","quantity":1,"type":"sku","image_uri":"https:\/\/pushys.local\/static\/frontend\/Magento\/luma\/en_AU\/Magento_Catalog\/images\/product\/placeholder\/.jpg","item_uri":"https:\/\/pushys.local\/config-prod-no-weight.html","product_code":"config prod no weight-1-2"}],"cart_reference":"34"},"config":{"redirect_uri":"https:\/\/pushys.local\/zipmoneypayment\/complete\/"},"created":"2020-01-15T03:14:42+00:00","state":"created","metadata":{}} [] []
[2020-01-15 03:14:43] zipMoneyLog.INFO: Successful to get redirect url [ https://my.sandbox.zipmoney.com.au/?co=co_9od6Yvfkwas0BVZqwEPuD3&m=20e7d8c2-1fb3-4941-9e57-1b0796344d37 ]  [] []
[2020-01-15 03:14:56] zipMoneyLog.DEBUG: On Complete Controller [] []
[2020-01-15 03:14:56] zipMoneyLog.DEBUG: Result:- %s [] []
[2020-01-15 03:14:56] zipMoneyLog.DEBUG: Current Customer Id:- %s Quote Customer Id:- %s Quote checkout method:- %s [] []
[2020-01-15 03:14:56] zipMoneyLog.DEBUG: Quote Grand Total:- 150.0000 Quote Customer Id:-  Checkout Method:- guest [] []
[2020-01-15 03:14:58] zipMoneyLog.INFO: Successfull to place the order [] []
[2020-01-15 03:14:58] zipMoneyLog.DEBUG: Shipping Required:- Yes [] []
[2020-01-15 03:14:58] zipMoneyLog.DEBUG: Gift Card Amount:- 0 [] []
[2020-01-15 03:14:58] zipMoneyLog.DEBUG: 150-0-0-150 [] []
[2020-01-15 03:14:58] zipMoneyLog.DEBUG: Charge Payload:- {"authority":{"type":"checkout_id","value":"co_9od6Yvfkwas0BVZqwEPuD3"},"amount":150,"currency":"AUD","capture":true,"order":{"reference":"000000013","shipping":{},"items":[{"name":"config prod no weight","amount":150,"reference":"19","quantity":1,"type":"sku","image_uri":"https:\/\/pushys.local\/static\/frontend\/Magento\/luma\/en_AU\/Magento_Catalog\/images\/product\/placeholder\/.jpg","item_uri":"https:\/\/pushys.local\/config-prod-no-weight.html","product_code":"config prod no weight-1-2"}]},"metadata":{}} [] []
[2020-01-15 03:14:59] zipMoneyLog.DEBUG: ApiError:- [400] Error connecting to the API (https://api.sandbox.zipmoney.com.au/merchant/v1/charges)-{"error":{"code":"request_invalid","message":"There are errors with the request, please see error items for more detail","details":[{"name":"Order.Shipping.Pickup","message":"Must have shipping address or allow pickup in store"}]}} [] []
[2020-01-15 03:14:59] zipMoneyLog.DEBUG: Cancelling the order [] []
[2020-01-15 03:14:59] zipMoneyLog.DEBUG: Could not process the payment [] []
[2020-01-15 03:14:59] zipMoneyLog.INFO: In errorAction [] []
[2020-01-15 03:14:59] zipMoneyLog.INFO: An error occurred. [] []`

You can see the error message "Must have shipping address or allow pickup in store"

Please check this,
Thanks

**Comment by benzhangzip** [comment] 2020-01-20 00:42
Hi @KiuNguyen,

Thank you for reporting issue, the error you have got is related to the shipping address in the charge API.
As you could see, the checkout API is successful, getting your checkout flow using pick up in store "shipping":{"pickup":true} as we try to detect your shipping address, if not found we assume it is pick up in store, as by default Magento2 did not provide click and collect feature.

The issue is in the charge API it could not detect shipping address from the order or quote, some company implemented click and collect solution with using "Store Address" to be shopper "Shipping Address" so that order still have shipping address instead of being empty.

In your solution it seems you just keep the shipping address empty when placing order.

The possible solution to fix this is change the /vendor/zipmoney/magento2/Helper/Payload.php file
on public function getShippingDetails()
before return $shipping; add the following code to fix the charge issue
`
if ($shipping->getPickup() === null) {
    $shipping->setPickup(true);
}
`

Hope this helps, and we will look into better support click and collect in the new release.

**Comment by benzhangzip** [comment] 2020-01-20 00:53
This error has nothing to do with the configurable product, it is just not working with your empty shipping address approaches for implementing your click and collect solution.

**Comment by benzhangzip** [comment] 2020-01-21 05:56
Closing the issue as supporting click and collect need merchant to do it as there are so many way of implementing that, just when it is click and collect, make sure the API payload getShippingDetails() return $shipping->setPickup(true); it is very difficult for plugin to detect your site is click and collect, only merchants know the rule.

**Closed by benzhangzip** 2020-01-21 05:56 UTC
